Docs - Hamlet Deploy Application
hamlet-io/docs pull request #103
Opened 2021-03-04 07:49 UTC by RossMurr4y

## Description

Adds technical reference documentation for the individual parts of Hamlet Deploy.

## Target Audience

- [ ] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [ ] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [x] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [ ] I have added appropriate labels to this PR.
- [ ] I have added this to the `hamlet roadmap` project.

2021-03-05 00:49 UTC, roleyfoley requested changes

2021-03-05 00:49 UTC, roleyfoley commented on sidebars.js
> +            'hamletdeploy/software/aws',
Should this be under a reference section? Not our current component reference but inline with the divisio guide, this would be technical reference docs right? 

So from the side bar nav perspective

- reference
   - Software Components 
     - cli 
     - executer
     - ... 
   - Blueprint Reference ( our current blueprint reference page )

2021-03-05 00:49 UTC, roleyfoley commented on sidebars.js
> +            'hamletdeploy/software/aws',
Since this whole docs site is about hamlet deploy not sure that we need that in the nav bar

2021-03-05 02:44 UTC, RossMurr4y commented on sidebars.js
> +            'hamletdeploy/software/aws',
I actually didn't know what to call it and figured someone would provide me a better name so just used what came to mind rather than get hung up on that.

I'll fix this up now.

2021-03-09 01:35 UTC, RossMurr4y commented
Structure has since been updated in a different PR, and this one has been rebased.

2021-03-09 01:36 UTC, roleyfoley requested changes

2021-03-09 01:36 UTC, roleyfoley commented on docs/reference/software/aws.md
> +The AWS Provider Plugin contains aws-specific seed data as well as the implementation routines specific to the provider. The Provider Plugin builds upon the data models established within the [Hamlet
Should these just be part of the library? I.e. under the engine section link to the library which shows the plugins available? 

Otherwise I think this would end up duplicating what's in the library

2021-03-10 00:45 UTC, RossMurr4y commented on docs/reference/software/aws.md
> +The AWS Provider Plugin contains aws-specific seed data as well as the implementation routines specific to the provider. The Provider Plugin builds upon the data models established within the [Hamlet
Excellent idea, less overhead that way. Will update.

2021-03-10 01:21 UTC, roleyfoley requested changes

2021-03-10 01:21 UTC, roleyfoley commented on docs/reference/software/engine.md
> +
I think you've described plugins here not modules

Plugins are our packaging for functionality, modules are a way to use hamlet

2021-03-10 22:49 UTC, RossMurr4y commented on docs/reference/software/engine.md
> +
Yep, got them mixed up!

Updated : https://github.com/hamlet-io/docs/pull/103/commits/7577ce401dced02f8885edd5290569277e955d98

2021-03-10 23:36 UTC, merged