docs: link to arch decision logs
hamlet-io/docs pull request #104
Opened 2021-03-05 05:41 UTC by RossMurr4y

## Description

- Creates a link in the documentation to the Architectural Decision Logs
- moves content to a more appropriate location in the docs sidebar

- at a later time, we could perhaps move the logs to the site in a more formal manner
- this approach in the short term will ensure that the documentation is readily available and centralised

## Target Audience

- [ ] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [ ] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [x] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [ ] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [ ] I have added appropriate labels to this PR.
- [ ] I have added this to the `hamlet roadmap` project.

2021-03-05 05:48 UTC, roleyfoley requested changes
I also thought about making them available on the site, but ended up being against it. Keep the ADR's simple means that we can chage anything with hamlet ( including the docs proces s) and the ADRs are just sitting as raw documents that don't need work to publish etc. 

IF people are reading them they will be pretty comfortable with the project

2021-03-05 05:48 UTC, roleyfoley commented on docs/reference/software/adr.md
> +ADR for short, the [Architectural Decision Records](https://github.com/hamlet-io/architectural-decision-log) repository serves to document design and development decisions for Hamlet Deploy. It follo
Not sure this really fits in here... 
The cli, container and executor are used by people and are software components that we develop. 

ADR is more part of the contirbuting process rather than a software that we create

2021-03-09 01:27 UTC, RossMurr4y commented on docs/reference/software/adr.md
> +ADR for short, the [Architectural Decision Records](https://github.com/hamlet-io/architectural-decision-log) repository serves to document design and development decisions for Hamlet Deploy. It follo
Agreed, I've removed.

2021-03-09 01:28 UTC, merged

2021-03-09 01:28 UTC, RossMurr4y commented
Merging, as this PR is now just a restructuring of documentation which I've already discussed with @roleyfoley in person. The newly contributed link to ADR's has been removed.