docs: hamlet learn guide for a fast/simple workspace install
hamlet-io/docs pull request #106
Opened 2021-03-10 05:49 UTC by RossMurr4y

## Description

Creates a simple guide to setting up a basic development workspace.

## Motivation and Context

Hamlet Deploy is a modular application and it can be configured a number of different ways depending on a users host OS and preferences. A basic guide gives other guides a common ground from which to assume users to be operating.

## How Has This Been Tested?

n/a

## Types of changes

- [x] Docs
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2021-03-10 05:57 UTC, roleyfoley commented
Do we still need this? 
https://github.com/hamlet-io/docs/tree/master/docs/contribute/setup 

OR is that considered separate?

2021-03-10 07:46 UTC, roleyfoley requested changes

2021-03-10 07:46 UTC, roleyfoley commented on docs/learn/workspace.md
> +docker pull hamletio/hamlet
```suggestion
# in your current container 
exit 

# from your local terminal
docker pull hamletio/hamlet
docker run -it --volume ~/hamletdeploy:/home/hamlet/cmdb hamletio/hamlet
```

If this is aimed at docker newbies then it probably needs those steps as well

2021-03-10 07:46 UTC, roleyfoley commented on docs/learn/workspace.md
> +This will start an interactive terminal inside of the _hamletio/hamlet_ container, and bring along for the ride your _hamletdeploy_ directory.
```suggestion
This will start an interactive terminal inside of the _hamletio/hamlet_ container, and make the _hamletdeploy_ directory available in the container.
```

Bring along might be a bit confusing for someone who has looked up how docker works a little bit

2021-03-10 07:46 UTC, roleyfoley commented on docs/learn/workspace.md
> +We'll want a directory on our local machine that can be used to store all of our work so lets make one now.
```suggestion
Docker storage is removed after the container stops, so we'll want a directory on our local machine that can be used to store all of our work so lets make one now.
```

Again a little help with understanding docker if people want search terms

2021-03-10 07:46 UTC, roleyfoley commented on docs/learn/workspace.md
> +First, in the terminal change into a directory that works for you you and then make a new directory for Hamlet Deploy.
```suggestion
First, in your local terminal change into a directory that works for you you and then make a new directory for Hamlet Deploy.
```

2021-03-10 07:46 UTC, roleyfoley commented on docs/learn/workspace.md
> +A basic understanding of working on the command-line is sufficient to follow along with Learn guides. The Docker container we are going to be using built upon [Debian](https://www.debian.org) operati
Do we need to go to debian specifically? Might be better to say using the bash terminal. We don't actually use anything specific to debian, more specific to bash

2021-03-11 00:25 UTC, RossMurr4y commented
> Do we still need this?
> https://github.com/hamlet-io/docs/tree/master/docs/contribute/setup
> 
> OR is that considered separate?

We do not, you are right.

As we go with documentation I intend to remove the older placeholders now we have a stronger understanding of what is required.

What is there may be helpful to some (well, if they weren't just placeholders mostly) however ultimately a users workspace is up to them to setup and configure. 

This PR gives you the "get up and going fast" method, each of the GitHub repositories contain individual installation and configuration instructions and so a user is free to combine that information.

Down the road more "advanced" setups for heavy Hamlet Deploy development might warrant a blog post containing a complete `.devcontainer` file for VSCode, but I think it clutters and confuses as it is now.

2021-03-11 00:29 UTC, RossMurr4y commented on docs/learn/workspace.md
> +docker pull hamletio/hamlet
What are your thoughts on who it should target?

[+] potentially more accessible to docker newbies if we assume no prior experience
[-] as a consequence the documentation gets a small amount of bloat. (nothing major, its just not as sleek and brief)

2021-03-11 00:34 UTC, RossMurr4y commented on docs/learn/workspace.md
> +A basic understanding of working on the command-line is sufficient to follow along with Learn guides. The Docker container we are going to be using built upon [Debian](https://www.debian.org) operati
Bash doesn't explain the whole filesystem navigation changes though, does it ? And that was my primary concern here - the commands provided will be sufficient on their own but having an understanding of directory navigation on a linux OS is a big help to following along and for pure Windows developers its a bit of a brave new world.

2021-03-11 00:59 UTC, roleyfoley commented on docs/learn/workspace.md
> +A basic understanding of working on the command-line is sufficient to follow along with Learn guides. The Docker container we are going to be using built upon [Debian](https://www.debian.org) operati
maybe linux + bash then rather than debian. 
cd ls etc are linux or shell commands rather than a specific thing for debian

2021-03-11 01:14 UTC, roleyfoley commented on docs/learn/workspace.md
> +docker pull hamletio/hamlet
I think the target is ok, just needs to be consistent. 
Any one who understands docker will see this is standard fare and ignore it

2021-03-11 06:22 UTC, RossMurr4y commented on docs/learn/workspace.md
> +A basic understanding of working on the command-line is sufficient to follow along with Learn guides. The Docker container we are going to be using built upon [Debian](https://www.debian.org) operati
Cool, have fixed this up in c3c5e20

2021-03-12 05:57 UTC, roleyfoley approved these changes

2021-03-12 05:57 UTC, merged