feat: 8.4 release post
hamlet-io/docs pull request #148
Opened 2022-01-06 04:16 UTC by roleyfoley

## Intent of Change

- Documentation (new or update to existing)

## Description

- Adds a blog post for the 8.4 release of hamlet

## Motivation and Context

Show off what we did in this release

## How Has This Been Tested?

## Related Changes

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

2022-01-06 05:09 UTC, ml019 approved these changes
Thanks for packaging this up.

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +With deployment testing we have made a couple of updates to make testing easier and provide better control over the configuration of tests
```suggestion
With deployment testing we have made a couple of updates to make testing easier and provide better control over the configuration of tests:-
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +- When configuring testing tools you can now provide configuration options to the testing tools. This allows you to disable particular checks or enforce the use of a particular framework format when
```suggestion
- When configuring testing tools you can now provide configuration options to the testing tools. This allows you to disable particular checks or enforce the use of a particular framework format when working with checkov.
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +
```suggestion
Azure deployments have been updated to more closely align with the changes to the AWS stack management processes to ensure that a consistent approach is used across the two  providers.

```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +We've made a range of changes to both the cli and bash backend to make it easier to work with hamlet
```suggestion
We've made a range of changes to both the cli and bash backend to make it easier to work with hamlet:-
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +- dos2unix has been removed from bash scripts, if this is required it will need to managed outside of hamlet from now on. Git mostly handles this process anyway
```suggestion
- dos2unix has been removed from bash scripts. If this is required, it will need to be managed outside of hamlet from now on. Git mostly handles this process anyway
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +- If your are using the URL or containerregsitry image sources you can skip pulling the image by setting the env var `HAMLET_SKIP_IMAGE_PULL=true` when running a deployment. This is handy when you ar
```suggestion
- If your are using the URL or containerregistry image sources you can skip pulling the image by setting the env var `HAMLET_SKIP_IMAGE_PULL=true` when running a deployment. This is handy when you are verifying a deployment
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +This release we added a couple of components and made some minor updates to align naming
```suggestion
This release we added a couple of components and made some minor updates to align naming:-
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +- EFS rename to fileshare: the EFS component has been renamed to fileshare to provide vendor agnostic naming for the component and allow for implementing other engines in the same fileshare functiona
```suggestion
- EFS rename to fileshare: the EFS component has been renamed to fileshare to provide vendor agnostic naming for the component and allow for implementing other engines in the same fileshare functionality.
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +The AWS plugin has had a range of updates to support different services on our current components
```suggestion
The AWS plugin has had a range of updates to support different services on our current components:-
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +- Filters can be used on topic subscriptions to control the messages sent to a particular subscription
```suggestion
- ECS Service/Task now supports specifying the number of GPUs required for a Container
- MTA inbound and out support has been implemented
- Filters can be used on topic subscriptions to control the messages sent to a particular subscription
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +- When deploying a directory component a route53 resolver is added to route DNS requests from the standard AWS DNS server to the AD servers. This removes the need for creating DHCP chagnes or manuall
```suggestion
- When deploying a directory component a route53 resolver is added to route DNS requests from the standard AWS DNS server to the AD servers. This removes the need for creating DHCP changes or manually configuring your DNS servers on instances
```

2022-01-06 05:09 UTC, ml019 commented on blog/2021-12-16-Release-v8.4.md
> +The Azure plguin has had some updates focussing on Networking and directories
```suggestion
The Azure plugin has had some updates focussing on networking and directories:-
```

2022-01-06 05:10 UTC, ml019 commented
@roleyfoley should have pressed the request changes button. All fairly minor grammar/spelling etc.

2022-01-11 06:21 UTC, silvergelatin requested changes
Document has been reviewed for typos and readability/clarity.

2022-01-11 06:21 UTC, silvergelatin commented on blog/2021-12-16-Release-v8.4.md
> +- **orphaned deployments are always first:** A bug around the orphaned deployment processing meant that they were not being found. This has now been resolved and orphaned deployments will now be proc
```suggestion
- **orphaned deployments are always first:** A bug related to orphaned deployment processing meant that orphaned deployments  were not being found. This has now been resolved and orphaned deployments will now be processed before other deployments to ensure they don't cause issues when running updates.
```

2022-01-11 06:21 UTC, silvergelatin commented on blog/2021-12-16-Release-v8.4.md
> +To see the full set of changes check out the CHANGELOGS for each of the hamlet services below
```suggestion
To see the full set of changes check out the CHANGELOGS for each of the hamlet services below:
```

2022-01-11 06:35 UTC, roleyfoley commented
Thanks @silvergelatin Handy review and thanks for catching all my weird casing :)

2022-01-12 22:10 UTC, ml019 approved these changes

2022-01-12 22:10 UTC, merged