WIP - Hamlet Integrations with Jenkins Docs
hamlet-io/docs pull request #53
Opened 2020-08-19 05:12 UTC by RossMurr4y

## Description

Implements an "Integrations" section of the docs site intended for documenting/showcasing hamlet integrations with other products.

## Target Audience

- [x] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [ ] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [x] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [x] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2020-08-19 05:13 UTC, RossMurr4y commented
Created as WIP until the content is copied across. For now its just an in-place structure, I still need to move the content across from other sources.

2020-08-27 00:36 UTC, RossMurr4y commented
PR is ready for review - I have excluded the documenting of the "script library" section as the whole PR was getting too big and will take too long too review, but will come back to it and have marked it as under construction.

2020-08-28 06:29 UTC, roleyfoley requested changes

2020-08-28 06:29 UTC, roleyfoley commented on docs/components/ecr.md
> +title: The ECR Component
We don't currently have an ECR component, also are we going to be doing these pages for all components?

2020-08-28 06:29 UTC, roleyfoley commented on docs/integrations/jenkins/examplelibrary/examples/dotproperties/dotproperties.md
> +## Creating a Dotproperties
I think this might be better as properties files. Properties files are an actual thing from Java I believe and that's the format that Jenkins bases these on

2020-08-28 06:29 UTC, roleyfoley commented on docs/integrations/jenkins/scriptlibrary/index.md
> +---
Given that we haven't used these in the examples should we worry about them?

2020-09-08 01:44 UTC, RossMurr4y commented on docs/components/ecr.md
> +title: The ECR Component
I am torn between the idea that the documentation for components should be generated with the schema by hamlet itself, and also by the idea that some components do require fairly in-depth coverage. Whilst that can still be defined and generated alongside the component, it leaves the question as to where such documentation belongs - the reference data, or should each component have their own page? Or should each reference data object receive its own page, including any documentation generated?

Regardless, I will remove these components for now. I was trying to create pages to link to, but it looks like that approach is causing more trouble than its worth at this stage. Updated 5d9f167

2020-09-08 01:53 UTC, RossMurr4y commented on docs/integrations/jenkins/examplelibrary/examples/dotproperties/dotproperties.md
> +## Creating a Dotproperties
No worries-  I was unaware of that convention and so had run with the idea of `dotfiles`, the convention used for storing `.<filename>` under source control.

Updated in 5497bba

2020-09-08 02:00 UTC, RossMurr4y commented on docs/integrations/jenkins/scriptlibrary/index.md
> +---
I have moved them to the __legacy dir for the time being in case we wish to add them in later. 7810713

2020-09-09 10:56 UTC, roleyfoley approved these changes

2020-09-09 10:56 UTC, merged