docs(profiles): initial docs for profiles
hamlet-io/docs pull request #54
Opened 2020-08-21 07:55 UTC by RossMurr4y

## Description

Document the design and application of `Profiles`.

Whilst Reference Data profiles work under the same pattern, they have their own section which is not covered by this PR. I have however staged headings here for that section so that I can create links to it now. Future changes to the headings will be captured by the Broken Link Checker and have to be fixed before committing.

## Target Audience

- [x] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [x] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2020-08-28 06:37 UTC, roleyfoley requested changes

2020-08-28 06:37 UTC, roleyfoley commented on docs/foundations/inputs/references.md
> +## WAF Profiles
Do we need to document them like this? would it be better to generate a reference page outlining them instead

2020-08-28 06:37 UTC, roleyfoley commented on docs/foundations/profiles.md
> +---
I think this page actually covers deployment and policy profiles more than it does the profiles in general

2020-08-28 06:37 UTC, roleyfoley commented on docs/foundations/profiles.md
> +}
The only profiles available at all levels are `Deployment` and `Policy` the other profiles are only available at the component level as each component may or may not need these profiles. 

Profiles other than `Deployment` and `Policy` can be applied to components through Deployment and Policy Profiles

2020-08-28 06:37 UTC, roleyfoley commented on docs/foundations/profiles.md
> +Security Profiles allow a forced override of all other Profile types. They are intended to allow a security team to set scope-wide mandatory configuration.
I think we should remove this and document other profiles in their reference guide

2020-08-28 06:37 UTC, roleyfoley commented on docs/foundations/profiles.md
> +
This is only true for `Deployment` and `Policy` Profiles

2020-09-08 00:56 UTC, RossMurr4y commented on docs/foundations/inputs/references.md
> +## WAF Profiles
They will have their own reference page with all the "reference data" objects. I was just creating this list of heading so that I could create hyperlinks to them as they are. I agree that their documentation - and for the other reference data too - should be coming from the schema generation. We have not yet implemented this though, and by at least having headings here for us to later complete, they are captured and not forgotten about in the event our plans for document generation change.

2020-09-08 01:04 UTC, RossMurr4y commented on docs/foundations/profiles.md
> +---
Whilst the % of page content is more dedicated to those two, the purpose and design of profiles in general is still covered here. Are you looking for a rename of the page so its just those two, or do you feel it needs more content towards profiles in general? I am trying to be succinct but if there is more explanation required then this page is likely the best place for it (to prevent too splitting it up, which I'm trying to avoid)

2020-09-08 01:26 UTC, RossMurr4y commented on docs/foundations/profiles.md
> +}
Updated this one in 5953438

2020-09-08 01:28 UTC, RossMurr4y commented on docs/foundations/profiles.md
> +Security Profiles allow a forced override of all other Profile types. They are intended to allow a security team to set scope-wide mandatory configuration.
No problem - I've updated in 6b5b6da

2020-09-08 01:31 UTC, RossMurr4y commented on docs/foundations/profiles.md
> +
Cheers, updated in 6b5b6da

2020-09-09 10:58 UTC, roleyfoley commented on docs/foundations/profiles.md
> +---
Based on the changes to the rest of the document I think this is fine to leave as it is. When we look at moving to snippets for these profiles then we can rename this file

2020-09-09 11:05 UTC, roleyfoley approved these changes

2020-09-09 11:05 UTC, merged