feat: implemented react-data-table-component
hamlet-io/docs pull request #64
Opened 2020-10-08 08:59 UTC by RossMurr4y

## Description

Implement `react-data-table-component` product to handle reference data table management.

## Target Audience

- [x] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [x] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [x] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [ ] I have added appropriate labels to this PR.
- [ ] I have added this to the `hamlet roadmap` project.

2020-10-13 00:32 UTC, roleyfoley requested changes
- Can we change the background colour so that the table entries aren't using the same colour as the background? 
- Some more whitespace between each component would make it easier to follow each component 
- The component top level header should be more distinct - Thinking a centred H1 tag would make more sense - combined with the whitespace that should make them pretty obvious 

- Default values seem to be a joined string, comma separated or pipe separated would be great  

- Removing `component Schema` might remove some of the noise around the headings and make them stand out more

- mandatory doesn't appear to be showing

2020-10-13 02:32 UTC, RossMurr4y commented
@roleyfoley  cheers I'll add those shortly.

Shall I add the JSON structure examples in again? Any thoughts on their formatting?

2020-10-13 02:50 UTC, roleyfoley commented
> @roleyfoley cheers I'll add those shortly.
> 
> Shall I add the JSON structure examples in again? Any thoughts on their formatting?

Yeah I think its handy and makes it a bit easier to understand how the component is structure 

So I guess base layout would be 

```
Heading

JSON Structure 

Detailed Table
```

2020-11-23 01:37 UTC, roleyfoley approved these changes

2020-11-23 01:37 UTC, merged