Docs - Links
hamlet-io/docs pull request #66
Opened 2020-11-04 00:53 UTC by RossMurr4y

## Description

Revisited the Links documentation.

## Target Audience

- [x] hamlet users
- [ ] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [x] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2020-11-22 21:04 UTC, ml019 commented on docs/foundations/links.md
> +                                "Instance" : "",
Should these be defined as they match the target? The text discusses defining these where they don't match the target whereas this is the opposite example.

2020-11-23 00:28 UTC, RossMurr4y reviewed
I have updated this in 6c68160 as per our discussion @ml019

2020-11-23 00:28 UTC, RossMurr4y commented on docs/foundations/links.md
> +                                "Instance" : "",
Trying to understand the issue but I can't see where I'm lacking in understanding.

* `example-db` has both an `instance` and `version`
* `example-function` has neither
* `example-db` linking to `example-function` must specify that the target has a difference from itself
  * that difference in both cases is that the target has neither, so an empty string is specified
* `example-function` linking to `example-db` must specify the inverse, where the difference is the name of the `instance` and `version`

Is that understanding correct and what's shown?

2020-11-23 01:28 UTC, roleyfoley requested changes

2020-11-23 01:28 UTC, roleyfoley commented on docs/foundations/links.md
> +Links define an association between two components. Linking one component (the link source) to another (the link target) implies that the source requires configuration information from the link targe
Links focus on components and don't know about the existence of deployment units

2020-11-23 01:28 UTC, roleyfoley commented on docs/foundations/links.md
> +Link's can be created at a number of solution scopes. Because of this they are considered a `metaparameter` and their definitions are kept outside of the component structure. You can view the structu
Not sure it would be at different scopes. Maybe that they are a common approach across components

2020-11-23 01:28 UTC, roleyfoley commented on docs/foundations/links.md
> +Whilst the precise implications of each link is defined by each provider, a link will ensure that the source component has been granted sufficient privilages on the destination component in order to
One of the main features of links is to apply specific permissions between two components. Each component offers component specific permissions which can another component can include in its configured permissions. This allows for fine grained automated permissions management

2020-11-24 21:14 UTC, ml019 requested changes

2020-11-24 21:14 UTC, ml019 commented on docs/foundations/links.md
> +By default, Link definitions assume that both source and target components have matching "Instance" and "Version" identifiers. Where this is not the case the difference must be explicitely assigned t
maybe better to say "example of `second-example-function` linking to `example-db` becuase that is the direction of the link

2020-11-25 00:25 UTC, RossMurr4y commented on docs/foundations/links.md
> +Links define an association between two components. Linking one component (the link source) to another (the link target) implies that the source requires configuration information from the link targe
Updated in e67dbce. 

I was attempting to convey that during the generation of a given deployment unit, the Links are often used to grant permissions to the other. But at their core, that is the behaviour of a Role. I have removed it - the role definition should cover that explanation on its own.

2020-11-25 00:29 UTC, RossMurr4y commented on docs/foundations/links.md
> +Link's can be created at a number of solution scopes. Because of this they are considered a `metaparameter` and their definitions are kept outside of the component structure. You can view the structu
Agreed, this wording doesn't accurately convey what I intended. I've updated it here: 4bc6820

2020-11-25 00:42 UTC, RossMurr4y commented on docs/foundations/links.md
> +Whilst the precise implications of each link is defined by each provider, a link will ensure that the source component has been granted sufficient privilages on the destination component in order to
Updated : e551931

2020-11-25 00:53 UTC, RossMurr4y commented on docs/foundations/links.md
> +By default, Link definitions assume that both source and target components have matching "Instance" and "Version" identifiers. Where this is not the case the difference must be explicitely assigned t
I decided to spell out each of the examples. Updated here: d9b6d09

2020-11-30 22:03 UTC, ml019 approved these changes
Looks fine as far as it goes.

2020-11-30 22:03 UTC, merged