Feat doc cmdbs
hamlet-io/docs pull request #67
Opened 2020-11-09 23:32 UTC by RossMurr4y

## Description

* Update the `Anatomy of a CMDB` documentation.
* Corrects a broken link to our first guide.

## Target Audience

- [x] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [x] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2020-11-10 01:16 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +A `root.json` file is required in the root directory that contains all CMDB's. This informs Hamlet that it has reached the origin of the CMDB's and not to search any higher for configuration.
Not sure I saw it that way I would say 

we have a Tenant with multiple accounts = accounts-cmdb 
we have Products which contain Solutions - you can have multiple instances of solutions, know as environments, each instance of a solution is deployed to an Account within the Tenant 

our standard CMDB structure ( accounts-cmdb and product-cmdbs ) then align with this concept

2020-11-10 01:16 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +
A solution is essentially a collection of components which create a functional service. We use components to define specific functions within the service, and from these definitions we create deployments of the solution. 

 we should mention that multiple instances of a solution can be deployed into an environment. I'm not sure we should go to Occurrence level at this stage, occurrences aren't really part of the CMDB. They are the representation of the CMDB used by the engine

2020-11-10 01:16 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +A `Product` is created for one or more `Accounts` and represents a whole project. Typically the largest of the CMDB's, the `Product` inherits any enforced behaviours from the `Account` and its `Tenan
Not sure I understand `A `Product` is created for one or more `Accounts` and represents a whole project` 

 I think this would be a Product contains multiple solutions, the solution can be deployed into multiple environments to manage the full lifecycle of your product. 

The solution defines the components, and supporting configuration aimed at deploying your product

2020-11-10 01:16 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +Configuration can be removed for individual scopes by defining it at as an empty object for that scope.
Might need to define the solution file a bit more, a solution file is actually any *.json file within the config/solutionsv2 tree 

You can add components ReferenceData and the whole kit and kaboodle at any level and it will be included as part of the CMDB building

2020-11-18 00:11 UTC, RossMurr4y commented on docs/foundations/anatomy.md
> +A `root.json` file is required in the root directory that contains all CMDB's. This informs Hamlet that it has reached the origin of the CMDB's and not to search any higher for configuration.
Hows this sound? f7dc966

2020-11-18 00:45 UTC, RossMurr4y commented on docs/foundations/anatomy.md
> +
Updated in https://github.com/hamlet-io/docs/pull/67/commits/9d3230cfee08f0bf8aabc79a7d1084769a3694f9

2020-11-18 00:50 UTC, RossMurr4y commented on docs/foundations/anatomy.md
> +A `Product` is created for one or more `Accounts` and represents a whole project. Typically the largest of the CMDB's, the `Product` inherits any enforced behaviours from the `Account` and its `Tenan
Updated: 8176095

2020-11-18 00:55 UTC, RossMurr4y commented on docs/foundations/anatomy.md
> +Configuration can be removed for individual scopes by defining it at as an empty object for that scope.
Updated 66731e3

2020-11-18 00:55 UTC, RossMurr4y commented
@roleyfoley  I have drafted changes to your comments when you have a moment

2020-11-24 03:11 UTC, roleyfoley requested changes

2020-11-24 03:11 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +A `Hamlet` is comprised of 2 kinds CMDB - the `Account` CMDB and the `Product` CMDB. An `Account` CMDB contains both the `Tenant` and all `Accounts` within it, whilst individual `Product` CMDBs conta
```suggestion
A `Hamlet` is comprised of an`Account` CMDB and one or many `Product` CMDBs. An `Account` CMDB contains both the `Tenant` and all `Accounts` within it, whilst individual `Product` CMDBs contain the `Solutions` that define and configure `Components` and `ReferenceData`. Each `Product` CMDB can contain multiple instances of a `Solution`, each corresponding to an `Environment`. Together, Hamlet deploys an instance of a `Solution` into an `Account` within the `Tenant`. 
```

2020-11-24 03:11 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +Multiple instances of a `Solution` can be deployed into an `Environment`, each one is known as a `Segment`.
```suggestion
Multiple `Solutions` can be deployed into an `Environment`, each one is known as a `Segment`. Each `Segment` implements its own services independent but generally related to the other segments
```

2020-11-24 03:11 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +At the top level of the structure, the CMDB identifier is the Tenant Id for `Tenants`, Account Id for `Accounts` and Product Id for `Products`. Hamlet uses this to identify the applicable ones at run
```suggestion
At the top level of the structure, the CMDB identifier is the Tenant Id for `Tenants`, Account Id for `Accounts` and Product Id for `Products`. During processing hamlet will use these files as markers to determine the appropriate files to include.
```

2020-11-25 23:34 UTC, merged