Docs - Hamlet Architecture
hamlet-io/docs pull request #68
Opened 2020-11-10 07:27 UTC by RossMurr4y

## Description

* Rewrite the existing documentation for Hamlet's architecture
* Rename file from `index.md` to `architecture.md`

## Target Audience

- [x] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [x] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2020-11-24 03:01 UTC, roleyfoley requested changes

2020-11-24 03:01 UTC, roleyfoley commented on docs/foundations/architecture.md
> +The `Engine` is responsible for compiling a `Solution` from all applicable input sources. Actions such as generating outputs and querying the `Solution` are undertaken by the `Engine`. The `Engine` i
I think this might be a little wrong. The engine is responsible for providing the instructions on what needs to be done by the executor. However the engine needs to be initially invoked by an executor.

2020-11-24 03:01 UTC, roleyfoley commented on docs/foundations/architecture.md
> +* Undertake a deployment to a cloud provider using generated templates
I think that's actually what all executors should do. Our current state doesn't quite represent the intention

2020-11-25 01:10 UTC, RossMurr4y commented on docs/foundations/architecture.md
> +# Engine Plugins
Updated here f9c9936

2020-11-25 01:11 UTC, RossMurr4y commented on docs/foundations/architecture.md
> +Plugins commonly implement new providers or output types as they have access to the compiled `Solution` and may define their own `Entrances`.
Also addressed in f9c9936

2020-11-25 01:35 UTC, RossMurr4y commented on docs/foundations/architecture.md
> +The `Engine` is responsible for compiling a `Solution` from all applicable input sources. Actions such as generating outputs and querying the `Solution` are undertaken by the `Engine`. The `Engine` i
Rewrote this here: 068dedf

2020-11-25 02:52 UTC, RossMurr4y commented on docs/foundations/architecture.md
> +* Undertake a deployment to a cloud provider using generated templates
Should we document for what we have, or what we intend to do? We can always update the documentation along with the design changes, no?

2020-11-25 23:30 UTC, roleyfoley commented on docs/foundations/architecture.md
> +* Undertake a deployment to a cloud provider using generated templates
I think if this is an architecture page we should outline the intention rather than current state.

2020-11-26 00:29 UTC, RossMurr4y commented on docs/foundations/architecture.md
> +* Undertake a deployment to a cloud provider using generated templates
@roleyfoley updated here: 4026962

I've combined the two explanations for the Executor. The foundations page explaining the architecture doesn't need to get into "this is bash and this is python" anyway.

2020-11-26 01:34 UTC, merged