Feat/attributesets
hamlet-io/docs pull request #77
Opened 2020-12-14 03:27 UTC by RossMurr4y

## Description

* Remove reference data for metaparameters
* Add reference data for attributesets

## Target Audience

- [x] hamlet users
- [x] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [x] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [ ] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2021-01-03 23:31 UTC, roleyfoley requested changes

2021-01-03 23:31 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +A `Product` contains multipe `Solutions` which can be deployed into `Environments` to manage the full lifecycle of the `Product`. The `Solution` defines the `Components` and supporting configuration
I don't think a user would put an AttirbuteSet into a solution. They are more internal development reference to make life easier for development aren't they?

2021-01-03 23:31 UTC, roleyfoley commented on docs/foundations/anatomy.md
> +Within a CMDB, any file under the path 'config/solutionsv2' contributes to a Hamlet `Solution` and can contain [`Components`](https://hamlet.io/reference/components), [`ReferenceData`](https://hamlet
Same here re: Attribute Sets

2021-01-03 23:31 UTC, roleyfoley commented on docs/foundations/profiles.md
> +Profiles are assigned to a scope though the `Profiles` Reference Data object, containing key/value pairs of the profile types and names. The Reference Data object is available to all scopes, however
```suggestion
Profiles are assigned to a scope though the `Profiles` Reference Data object, containing key/value pairs of the profile types and names. The Profiles object is available to all scopes, however only the Deployment and Policy profile types are available for assignment above the Component level. To implement a Component-level profile at a higher scope, they should be associated with either a Deployment or Policy profile.
```

2021-01-04 00:04 UTC, RossMurr4y commented on docs/foundations/anatomy.md
> +A `Product` contains multipe `Solutions` which can be deployed into `Environments` to manage the full lifecycle of the `Product`. The `Solution` defines the `Components` and supporting configuration
Yep you're right. Updated here in https://github.com/hamlet-io/docs/pull/77/commits/f79ad97ae2cd25ded3c2f5b1c69009465c8cfe30

2021-01-04 00:04 UTC, RossMurr4y commented on docs/foundations/anatomy.md
> +Within a CMDB, any file under the path 'config/solutionsv2' contributes to a Hamlet `Solution` and can contain [`Components`](https://hamlet.io/reference/components), [`ReferenceData`](https://hamlet
Updated here too https://github.com/hamlet-io/docs/pull/77/commits/6e823cfc759866a19c08ed795077fe81e1f61820

2021-01-04 00:19 UTC, merged