docs: blog article on implementing cfcofnito and githubidp modules
hamlet-io/docs pull request #94
Opened 2021-02-10 04:54 UTC by RossMurr4y

## Description

blog article on implementing cfcofnito and githubidp modules

## Target Audience

- [x] hamlet users
- [ ] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [ ] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [ ] New feature (Documenting something new)
- [x] Blog article

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [ ] I have added appropriate labels to this PR.
- [ ] I have added this to the `hamlet roadmap` project.

2021-02-10 04:55 UTC, RossMurr4y commented
Created as draft whilst I verify the order-of-operations outlined within are accurate

2021-02-11 23:16 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +- - - -
```suggestion
- - - 
```

2021-02-12 06:24 UTC, RossMurr4y commented
Marked ready for review

2021-02-15 01:14 UTC, roleyfoley requested changes

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Add the following to the Solution to configure the module  (non-relevant configuration is trimmed from the example) :
```suggestion
Add the following to the Solution to configure the module  :
```
Lets trim no relevant bits form the blog post too :)

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +With the _githubidp_ module configured, we can now update our original `userpool` to include  `userpoolauthprovider`.
```suggestion
With the _githubidp_ module configured, we now configure our `userpool` to include  `userpoolauthprovider`.  
```

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +The Module we are using includes externally sourced files for both the `lambda` and `apigateway`, so you do not need to provide these yourself.
I think the Github lambda function is the one that needs the build job. In that case they aren't externally sourced

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +## Configuring Modules: cfcognito
Probably need an explanation of what this one does. I.e. It enables OIDC compliant authentication at the Cloud front layer. This allows you to use Cognito to provide coarse ( i.e. in our out ) level access to all content behind the Cloud front distribution.

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +This module includes a lambda ( deployment unit `<id>_lmb`) that must be specifically deployed into the **us-east-1** (the “global” region for AWS). For this to happen we must override any other Regi
```suggestion
This module includes a lambda ( deployment unit `<id>_lmb`) that must be specifically deployed into the **us-east-1** (required for cloudfront Lambda@Edge). For this to happen we must override any other Region configuration you may have, but only for this one component. The below example will apply it product-wide, only for the component with an `id` of `door-lmb`:
```

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +As this module adds the `cdn` into our Solution, we can now include our `userpoolclient` sub-component on our `userpool`. So that it picks up the Callback URL information for the `cdn`, we need to pr
```suggestion
As this module adds the `cdn` into our Solution we now need to add a  `userpoolclient` sub-component on our `userpool` which will be used cloudfront to access the userpool. So that it picks up the Callback URL information for the `cdn`, we need to provide a Link on it to the `cdn` component configuration inside of the Module. 
```

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +And with that, your Single Page Application should be secured behind Github OAuth!
I think its probably better to leave out the certificate. Otherwise you'll need to cover generating them or link to somewhere that explains that

2021-02-15 01:14 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +And with that, your Single Page Application should be secured behind Github OAuth!
Also Since its a demo, I'd suspect that the cloudfront Url is good enough

2021-02-16 00:35 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Single Page Applications - or SPAs as they are more commonly called - are everywhere nowadays, alongside them on their rise in popularity are the numerous app frameworks that allow anyone to spin up
cheers, updated

2021-02-16 00:47 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +You will need to have configured a Hamlet Tenant, Account(s) and Product for our SPA, and have deployed all the “out-of-the-box” deployment-units.
Added :)

2021-02-16 00:48 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Within your selected Github organisation you will need to register a new [OAuth Application](https://docs.github.com/en/developers/apps/creating-an-oauth-app). Enter a placeholder Callback URL for th
Updated

2021-02-16 00:51 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Here’s our initial Solution configuration. We’ve added the Plugins, but the modules within them are not yet configured. Our `mgmt` tier has the definition for a single `userpool` I’ve simply called “
Good idea, I think what I had was more a reflection of me working out my steps than actually what needed to be conveyed.

2021-02-16 01:04 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +:::
Updated https://github.com/hamlet-io/docs/pull/94/commits/70177efd0b5f3b91983d61a4f5c3dd549ef8733d

2021-02-16 01:08 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Keen eyes may notice that I’ve not configured a `cdn` yet. This will be provided by our _cfcognito_ module, so we’ll start to see it’s deployment-unit once the module has been configured.
I included it because for anyone following along that might have an existing static site, they will run into the original problem I had - they likely already have a `cdn` configured and deployed and trying to use it won't work. 

They'll want to remove it at this point in things too, rather than later in the article when we configure the 2nd module - there is a lot of back-tracking involved.

Does that make sense or still think we can remove?

2021-02-16 01:14 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Add the following to the Solution to configure the module  (non-relevant configuration is trimmed from the example) :
😄 

Whilst I agree (and somewhat saw this coming) I think there's an argument to be made about explaining that the example isn't "complete". It's like stepping through an instructional book on programming. At some stage the author explains to you that the terminal prompt with be excluded from examples for formatting purposes.

However, that said - In explaining this just now I think my above comment stands for "tutorials", but is unnecessary for the type of documentation in a "blog" - they need to be brief and lean.

I have thus removed it 👍🏻

2021-02-16 01:15 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +With the _githubidp_ module configured, we can now update our original `userpool` to include  `userpoolauthprovider`.
Updated

2021-02-16 01:18 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +The Module we are using includes externally sourced files for both the `lambda` and `apigateway`, so you do not need to provide these yourself.
updated

2021-02-16 01:21 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +## Configuring Modules: cfcognito
Thanks for the wording - I've updated

2021-02-16 01:22 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +This module includes a lambda ( deployment unit `<id>_lmb`) that must be specifically deployed into the **us-east-1** (the “global” region for AWS). For this to happen we must override any other Regi
cheers, updated

2021-02-16 01:25 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +As this module adds the `cdn` into our Solution, we can now include our `userpoolclient` sub-component on our `userpool`. So that it picks up the Callback URL information for the `cdn`, we need to pr
cheers, updated

2021-02-16 01:38 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +In this article, I will be stepping through the process of using two of the recently published Hamlet modules - _cfcognito_ and _githubidp_. Used alongside a Hamlet Solution for a typical SPA deploym
yep, ill pull one from the diagrams provider if that works?

Asking rather than doing because the diagrams plugin has run into the same component-loading issue I was having yesterday with the `sharedtest` provider, only I can't seem to fix this one by specifying my providers. I'll get the diagram in once we've resolved that ticket.

2021-02-19 08:07 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +In this article, I will be stepping through the process of using two of the recently published Hamlet modules - _cfcognito_ and _githubidp_. Used alongside a Hamlet Solution for a typical SPA deploym
Was thinking of a more simple mermaid diagram like in the hello hamlet or in https://docs.hamlet.io/blog/2021/01/13/template-deploys

2021-02-19 08:08 UTC, roleyfoley commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +Keen eyes may notice that I’ve not configured a `cdn` yet. This will be provided by our _cfcognito_ module, so we’ll start to see it’s deployment-unit once the module has been configured.
I think if the blog is starting from an empty solution its probably best to leave it out. Part of this blog is highlighting that modules add components right?

2021-02-19 08:10 UTC, roleyfoley commented
Sorry missed that you'd answered some of the comments @RossMurr4y Just been through them

2021-02-21 23:25 UTC, RossMurr4y commented on blog/2021-02-10-spas-with-github-authentication-made-easy.md
> +In this article, I will be stepping through the process of using two of the recently published Hamlet modules - _cfcognito_ and _githubidp_. Used alongside a Hamlet Solution for a typical SPA deploym
Added a diagram in https://github.com/hamlet-io/docs/pull/94/commits/b40f7306e4a377921e3ab1e9671697085f1d0b67

2021-02-21 23:26 UTC, RossMurr4y commented
> Sorry missed that you'd answered some of the comments @RossMurr4y Just been through them

No worries. I've just added a diagram for review as well.

2021-02-24 04:41 UTC, roleyfoley commented
@RossMurr4y I've just pushed up a new commit on this PR with a few extra changes from what I've picked up from reviewing the post again. Please review these and make any updates you feel should be done

2021-02-24 04:41 UTC, roleyfoley approved these changes

2021-02-26 02:36 UTC, merged