[DRAFT] - Docs - Hamlet Learn
hamlet-io/docs pull request #99
Opened 2021-02-11 05:34 UTC by RossMurr4y

## Description

Hamlet Learn is to house all of the "tutorial"-type documentation
for the Hamlet Deploy project. These guided practical lessons
will provide exposure to the fundamental concepts of Hamlet,
whilst leaving the conceptual/reference/discussion documentation
for other sections of the site.

The tutorials are deliberately written to be approachable, fun and
not too serious, whilst not getting bogged down in the explanations.

## Target Audience

- [x] hamlet users
- [ ] hamlet framework developers (incl. plugins)

## Types of changes

#### Documentation
- [ ] Spelling / Syntax correction only
- [ ] Refactor (Documentation overhaul, or revising after changes to hamlet)
- [x] New feature (Documenting something new)
#### Site Design
- [ ] Refactor (No new or removed content.)
- [x] New Features & Content
- [ ] Docusaurus / Plugin version update.

## Followup Actions

- [x] None

## Checklist:

- [x] I have tested the changes locally - see [README.md](https://github.com/hamlet-io/docs/blob/master/README.md)
- [x] I have added appropriate labels to this PR.
- [x] I have added this to the `hamlet roadmap` project.

2021-02-15 07:08 UTC, RossMurr4y commented
Ready for review -viewable here : https://hamlet-docs-7f9c5zb1v.vercel.app/docs/learn/layers/intro

2021-02-15 21:49 UTC, ken9ross commented
In account layer:
Typo:
`Enter provider id: aws`
vs
`|   5 | provider id   | 012345678912 |`

Spelling: `documenatation`

2021-02-24 05:16 UTC, roleyfoley requested changes
I like the style and the quick little sections. Changes suggested are mostly syntax

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/blueprint.md
> +We certainly provided the `Name` and `Id`, but the remainder of this Environment configuration was contributed by the Shared Provider. An "integration" Environment is commonly required and understood
Don't know if we need to bring providers in completely here. Could this be something like

```
 your configuration isn't the only source of configuration for the blueprint. The engine actually comes with a collection of default and common configuration references. Lets have a look at the environment as an example
```

How we do this with plugins is probably a 200 level tutorial rather than a 100 level

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/blueprint.md
> +If your Layers define non-Provider Plugins to load (not yet covered) then they may also be contributing definitions in the same manner as the Provider Plugins.
This could be removed with the previous comment

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/intro.md
> +As an organisation grows more and more people want to have a say in the way that things are done. It's alright for them to talk the talk, but we know who the actual implementation of it all is going
This feels kinda clunky, I'm not sure it really covers what hamlet does or problems people might be having

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/intro.md
> +## A Layer-ed Approach
```suggestion
## A Layered Approach
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/intro.md
> +Hamlet captures a wholistic view of an organsations requirements, and applies each one across its entire scope. A particular security policy may be applied for just a single product, or across the en
```suggestion
Hamlet captures a holistic view of an organisations infrastructure deployment requirements, and applies them across its entire scope. A particular security policy may be applied for just a single product, or across the entire organisation. The implementation of that policy is the same either way, and in both cases it is only implemented the once - but the layer at which it is defined ensures it will apply across the scope it is intended.
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +A Product is an operational service that has its own lifecycle, often aligning with a organsation Project.
```suggestion
A Product is an operational service that has its own life-cycle and represents a single system. 
```

Project gets dicey as that isn't the full lifecycle of a product

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +There are a number of default Product types that can be used but here we've chosen the "base" Product - this will give us a well-rounded set of configuration to start us off.
```suggestion
There are a number of default Product types that we can generate but here we've chosen the "base" Product - this will give us a well-rounded set of configuration to start us off.
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +Prompt 3 here is asking us what the `Id` value is for the Domain our Product will use. If you recall, we defined our `Domains` object on the Tenant, as it is typically an organisationally owned resou
```suggestion
Prompt 3 here is asking us what the `Id` value is for the Domain our Product will use. If you recall, we defined our `Domains` object on the Tenant, since domain names need to be unique across the Organisation and may be required across a number of Accounts and Products. So reviewing that configuration we see that our new Tenant only has the one domain defined - `acmeinc`.
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +Nice and minimal Product configuration here. As is the case for every layer, we define our `Name` and `Id` for it, and our domain association is configured here too.
```suggestion
This is a basic Product configuration. All layers have an Id and Name field and each layer type adds its own configuration relevant to the product. Here the domain name that will be used by default for any public endpoints we deploy in this product
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +Our Solution directory looks to have made a created a number of files though, lets take a closer look.
```suggestion
Our Solution directory looks to have made a created a number of files, lets take a closer look.
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +Underneath this, the same has happened for our Segment layer too - however we've opted to go with the `default` segment name. We could create a `shared` Segment directory too, however in this instanc
Might be worth an explanation of an Environment and Segment

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/product.md
> +```
And an explanation for the Tier as well

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/tenant.md
> +Your terminal window should now look like this - if not, you might need to ensure you have Docker installed and configgured correctly.
```suggestion
Your terminal window should now look like this - if not, you might need to ensure you have Docker installed and configured correctly.
```

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/tenant.md
> +Your terminal window should now look like this - if not, you might need to ensure you have Docker installed and configgured correctly.
Do we have prereqs listed for the tutorials?

2021-02-24 05:16 UTC, roleyfoley commented on docs/learn/layers/tenant.md
> +An organisation will typically own one or more domains that they have purcahsed. Tracking these domains - even when presently unused, as is the case here - will allow Accounts and Products configured
```suggestion
An organisation will typically own one or more domains that they have purchased. Tracking these domains - even when presently unused, as is the case here - will allow Accounts and Products configured at a later time to make use of them. As we provided the CLI prompt with a domain owned by our Tenant, it has configured it here, however there are no certificates that use it currently.
```

2021-03-02 01:22 UTC, RossMurr4y commented on docs/learn/layers/blueprint.md
> +A quick review of our work so far will show you that our Account knows Tenant it belongs to. But though our Product does reference configuration defined on the Tenant (the "Domain") Hamlet doesn't in
I have reworded this now to better explain the relationship and provide a visual reference.

2021-03-02 01:28 UTC, RossMurr4y commented on docs/learn/layers/blueprint.md
> +:::
Have moved now, but not certain about the location you referenced as numbers have now changed with other updates. I've placed it after invoking the entrance - I feel like the question is more naturally answered afterwards, rather than pre-emptively.

2021-03-02 01:30 UTC, RossMurr4y commented on docs/learn/layers/blueprint.md
> +:::
I wanted to address overrides for default configuration. I think that is better handled in its own blog article / tutorial / how-to. Will remove it.

2021-03-02 01:38 UTC, RossMurr4y commented on docs/learn/layers/blueprint.md
> +We certainly provided the `Name` and `Id`, but the remainder of this Environment configuration was contributed by the Shared Provider. An "integration" Environment is commonly required and understood
Good idea, I've fixed that up.

2021-03-02 01:41 UTC, RossMurr4y commented on docs/learn/layers/intro.md
> +As an organisation grows more and more people want to have a say in the way that things are done. It's alright for them to talk the talk, but we know who the actual implementation of it all is going
Yeah I should have written the "intro" last rather than first. Will re-write this bit.

2021-03-02 02:32 UTC, RossMurr4y commented
I've now addressed all comments.

2021-03-02 10:56 UTC, roleyfoley commented on docs/learn/layers/blueprint.md
> +A quick review of our work so far will show you that our Account knows Tenant it belongs to. But though our Product does reference configuration defined on the Tenant (the "Domain") Hamlet doesn't in
Don't quite follow the intention with the domain reference on the tenant. 

This could be a point to introduce the layering concept. I.e. in the product.json it has specified a domain which isn't part of the CMDB itself. This is actually defined in the tenant cmdb. When the CMDB is processed all of the configuration under the root.json will be merged together. 

Becuase of this merge process the domain referenced in the product will now be available.

2021-03-03 00:39 UTC, RossMurr4y commented on docs/learn/layers/blueprint.md
> +A quick review of our work so far will show you that our Account knows Tenant it belongs to. But though our Product does reference configuration defined on the Tenant (the "Domain") Hamlet doesn't in
I suppose there are two things to be conveyed here:

- when I perform something I hamlet, how do all of these layers know which to use at any given time? How are they interconnected.
- layering the districts becomes the blueprint.

I was trying to convey the first, but there is a lot of value (and admittedly it was in my title in the intro) in using this opportunity to explain the latter too.  I'll split them out and submit another update for your review.

2021-03-03 00:52 UTC, roleyfoley commented on docs/learn/layers/blueprint.md
> +A quick review of our work so far will show you that our Account knows Tenant it belongs to. But though our Product does reference configuration defined on the Tenant (the "Domain") Hamlet doesn't in
I was thinking about this this morning, maybe its better that to start off with we don't add Domains or Certificates and make them a user defined configuration option. This would make it easier from the cookie cutter perspective, or we make domain definitions by default included in the product. This would leave the domain and merging different configuration sections for a more advanced topic

2021-03-03 02:42 UTC, RossMurr4y commented on docs/learn/layers/blueprint.md
> +A quick review of our work so far will show you that our Account knows Tenant it belongs to. But though our Product does reference configuration defined on the Tenant (the "Domain") Hamlet doesn't in
Updated here https://github.com/hamlet-io/docs/pull/99/commits/c03f1359f9cc1de582164d9adfa2176b0e8000f8 - I've intentionally not included Policy Profiles in the description of layering here as it feels like too much.

2021-03-03 03:11 UTC, roleyfoley approved these changes

2021-03-03 03:11 UTC, merged